[project]
name = "first-agent-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "duckduckgo-search>=8.0.2",
    "gradio>=5.33.0",
    "markdownify>=1.1.0",
    "pandas>=2.3.0",
    "pytz>=2025.2",
    "requests>=2.32.3",
    "smolagents==1.13.0",
]
